"""migration

Revision ID: bd5a558b568c
Revises: 78ac62330d19
Create Date: 2025-02-22 21:14:03.756254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5a558b568c'
down_revision: Union[str, None] = '78ac62330d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paintings', 'technique_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('paintings', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paintings', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('paintings', 'technique_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
