# Generated by Django 5.1.4 on 2025-01-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyname',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_properties', to='cabinet.artist'),
        ),
        migrations.AlterField(
            model_name='propertyname',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
