# Generated by Django 5.1.4 on 2025-01-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_propertyname_artist_alter_propertyname_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='customer_user',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='customer_user',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='requestorder',
            old_name='customer_user',
            new_name='bidder',
        ),
    ]
