# Generated by Django 5.1.4 on 2025-01-04 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_lot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='author',
        ),
        migrations.AddField(
            model_name='bidlot',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_lots', to='cabinet.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedlot',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_lots', to='cabinet.artist'),
            preserve_default=False,
        ),
    ]
