# Generated by Django 5.1.4 on 2025-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_rename_customer_user_bid_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=64),
        ),
    ]
