# Generated by Django 5.1.4 on 2025-01-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_property_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='main_photo',
            new_name='photo',
        ),
    ]
