# Generated by Django 5.1.4 on 2025-01-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_rename_main_photo_lot_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='value',
            new_name='amount',
        ),
    ]
