# Generated by Django 5.1.4 on 2025-01-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_rename_value_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='bidder',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='requestorder',
            old_name='bidder',
            new_name='buyer',
        ),
    ]
