# Generated by Django 5.1.4 on 2025-01-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidlot',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
